apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: update-confluence-task
  namespace: default
spec:
  params:
    - name: page-id
      type: string
    - name: module-namespace
      type: string
  steps:
    - name: run-python
      image: python:3.9
      workingDir: /workspace/output
      script: |
        #!/bin/sh
        pip install requests
        curl -O https://raw.githubusercontent.com/NawalC/update-confluence-pipeline-/main/update_mdac.py
        python update_mdac.py $(params.page-id) $(params.module-namespace)
      env:
        - name: CONFLUENCE_URL
          valueFrom:
            secretKeyRef:
              name: confluence-creds
              key: url
        - name: JSESSIONID
          valueFrom:
            secretKeyRef:
              name: confluence-session-cookie
              key: JSESSIONID

