apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: hello-world-pipeline
  namespace: default
spec:
  params:
    - name: parent-page-id
      type: string
    - name: space-key
      type: string
  tasks:
    - name: publish
      taskRef:
        name: create-hello-world-page
      params:
        - name: parent-page-id
          value: "$(params.parent-page-id)"
        - name: space-key
          value: "$(params.space-key)"
