apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: hello-world-pipeline
  namespace: default
spec:
  params:
    - name: parent-page-id
      type: string
    - name: space-key
      type: string
  tasks:
    - name: publish
      taskRef:
        name: create-hello-world-page
      params:
        - name: parent-page-id
          value: "$(params.parent-page-id)"
        - name: space-key
          value: "$(params.space-key)"



# /* 
# kubectl apply -f create-hello-world-page.yaml
# kubectl apply -f pipeline.yaml
# kubectl apply -f pipeline-run.yaml
# kubectl get pods -A
# kubectl logs -f hello-world-pipeline-run-publish-pod -c step-publish
# kubectl get pod hello-world-pipeline-run-publish-pod -o jsonpath="{.spec.containers[*].name}"
# kubectl logs -f hello-world-pipeline-run-publish-pod -c step-create-page
# kubectl logs hello-world-pipeline-run-publish-pod --all-containers
# kubectl delete pipelinerun pipeline-run
# kubectl get pipelinerun
# kubectl delete pipelinerun hello-world-pipeline-run */