apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: create-confluence-page
spec:
  params:
    - name: parent-page-id
      type: string
    - name: space-key
      type: string
    - name: module-name
      type: string
    - name: previous-version
      type: string
    - name: new-version
      type: string
  steps:
    - name: publish
      image: python:3.9
      env:
        - name: CONFLUENCE_USER
          valueFrom:
            secretKeyRef:
              name: confluence-creds
              key: user
        - name: CONFLUENCE_PAT
          valueFrom:
            secretKeyRef:
              name: confluence-creds
              key: pat
        - name: CONFLUENCE_URL
          valueFrom:
            secretKeyRef:
              name: confluence-creds
              key: url
      script: |
        #!/usr/bin/env python3
        import os
        import requests
        import base64
        import json

        user = os.environ["CONFLUENCE_USER"]
        pat = os.environ["CONFLUENCE_PAT"]
        base = os.environ["CONFLUENCE_URL"]
        parent_id = os.environ["PARENT_ID"]
        space = os.environ["SPACE_KEY"]
        module = os.environ["MODULE_NAME"]
        prev = os.environ["PREVIOUS_VERSION"]
        new = os.environ["NEW_VERSION"]

        title = f"Release - {module} {new}"

        table_html = f"""
        <table>
          <tr><th>Module</th><th>Previous Version</th><th>New Version</th></tr>
          <tr><td>{module}</td><td>{prev}</td><td>{new}</td></tr>
        </table>
        """

        payload = {
          "type": "page",
          "title": title,
          "ancestors": [{"id": parent_id}],
          "space": {"key": space},
          "body": {
            "storage": {
              "value": table_html,
              "representation": "storage"
            }
          }
        }

        auth = f"{user}:{pat}"
        encoded = base64.b64encode(auth.encode()).decode()
        headers = {
          "Authorization": f"Basic {encoded}",
          "Content-Type": "application/json"
        }

        print(f"Creating page under parent {parent_id} with title '{title}'")
        r = requests.post(f"{base}/rest/api/content", headers=headers, json=payload)

        if r.status_code in [200, 201]:
          print("Confluence page created successfully.")
        else:
          print(f"Failed with status {r.status_code}")
          print(r.text)
