apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: update-confluence-run
  namespace: default
spec:
  pipelineSpec:
    params:
      - name: page-id
        type: string
      - name: module-namespace
        type: string
    tasks:
      - name: update-page
        taskRef:
          name: update-confluence-task
        params:
          - name: page-id
            value: "$(params.page-id)"
          - name: module-namespace
            value: "$(params.module-namespace)"
  params:
    - name: page-id
      value: "229377" 
    - name: module-namespace
      value: "test-ns"
